<?php
$form=$this->form;
//$form= new Application_Form_Confirm();
$form->setAttrib(Application_Form_Confirm::attrSubmitText,'Снять с публикации');
?>
<ul class="h clearfix path">
	<li><a href="../">Объявления</a>/</li>
	<li><a href="<?=$this->url(array('controller'=>'ad','action'=>'edit','id'=>$this->obj->getID()));?>"><?php echo $this->obj->title;?></a>/</li>
	<li><b>Публикация</b></li>
</ul>
<p class="message">Снять с публикации запись "<?php echo $this->obj->title;?>"?</p>
<?php echo $form;?>