<!doctype html>  

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ --> 
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame 
       Remove this if you use the .htaccess -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Sarafan.fm - job</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!--  Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">


  <!-- CSS : implied media="all" -->
  <link rel="stylesheet" href="/css/style.css?v=5">
  <link rel="stylesheet" href="/css/facebook.css" type="text/css"/>
  <!-- Uncomment if you are specifically targeting less enabled mobile browsers
  <link rel="stylesheet" media="handheld" href="css/handheld.css?v=2">  -->
 
  <!-- All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -->
  <script src="/js/libs/modernizr-1.6.min.js"></script>
  <script>
 
  	window.fbAsyncInit = function() {  	  	  	  	  	
  		FB.init({
  		    appId  : '<?=$this->appID;?>',
  		    status : true, // check login status
  		    cookie : true, // enable cookies to allow the server to access the session
  		    xfbml  : true  // parse XFBML
  		  });
  	  	
  		FB.Canvas.setAutoResize();
	  	
	}
  
  </script>
</head>

<body class="facebook">
<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script>
</script>	



<header>
<? 
if ($this->is_main){
	?><h1 class="logo">Sarafan <span>Jobs</span></h1><?
}
else {
	?><a href="<? echo $this->url(array('controller'=>'facebook'),null,true);?>" class="logo" title="На главную">Sarafan <span>Jobs</span></a><?	
}
?>
<ul>
	<li><a href="<? echo $this->url(array('controller'=>'facebook','action'=>'manage'),null,true);?>">Добавить приложение</a></li>
	<li><a href="<? echo $this->url(array('controller'=>'facebook','action'=>'category'),null,true);?>">Объявления</a></li>
	<?
	if ($this->user && $this->user->is_post){
		?><li><a href="<? echo $this->url(array('controller'=>'facebook','action'=>'stat'),null,true);?>">Статистика</a></li><?
	}
	?>
</ul>
</header>
<section class="content">
<?
echo $this->layout()->content;
?>
</section>
<div class="clearfix"></div>
<footer>
&copy; <a href="http://sarafan.fm/" target="_top">sarafan.fm</a> <? echo date('Y');?>
</footer>
</div>
</body>
</html>